name: Github actions test
on: [workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - run: git clone --depth 1 https://github.com/google/shaderc-rs.git --branch v0.7.2
